micronaut:
  application:
    name: apiAluraFlix
  server:
    port: 5000

datasources:
  default:
    url: jdbc:h2:mem:aluraflix_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa.default.properties.hibernate:
  hbm2ddl.auto: none
  show_sql: true

flyway:
  datasources:
    default:
      enabled: true